#!/bin/bash
FLAMEGRAPH_DIR=~/work/FlameGraph
set -e

if [ ! -d "$FLAMEGRAPH_DIR" ]; then
    cd ~/work
    git clone https://github.com/brendangregg/FlameGraph.git
    cd -
fi

# record profiling data
perf record -g $*
perf script > out.perf

# post-process data
$FLAMEGRAPH_DIR/stackcollapse-perf.pl out.perf > out.folded

# generate SVG
$FLAMEGRAPH_DIR/flamegraph.pl --width 1900 --height 24 out.folded > flamegraph.svg

if [ -x /usr/bin/mimeopen ]; then
    /usr/bin/mimeopen flamegraph.svg
fi

