#!/usr/bin/perl
use 5.020; use warnings; use autodie;
use Data::Dumper;

my %params;
while (<STDIN>) {
    chomp;
    my @parts = split /=/;
    $params{$parts[0]} = $parts[1];
    print STDERR "$_\n";
}

my $protocol = $params{protocol};
my $username = $params{username};
my $host = $params{host};

if ($ARGV[0] eq "get") {
    my $password = `pass show $protocol/$username@$host`;
    print "password=$password\n";
} elsif ($ARGV[0] eq "store") {
    my $password = $params{password};
    `pass insert $protocol/$username@$host $password`;
}
