#!/bin/bash

# check if yubikey is present
ssh-add -l | grep -q 'cardno:000604887239' || exit 0

mbsync -a
notmuch new
notmuch tag +redmine -inbox -- from:redmine@ascolab.com
notmuch tag +support -inbox -- from:redmine@unifiedautomation.com
notmuch tag +phabricator -inbox -- from:phabricator@ascolab.com
notmuch tag +kropatz -inbox -- from:post@stb-kropacz.de

