#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null
else
    login=`pass show "$password" | awk '{ if (NR==2) { print $2 }}'`
    pass=`pass show "$password" | awk '{ if (NR==1) { print $1 }}'`
    if [ -z "$login"]; then
        # just type the password
        echo "$pass" | xdotool type --clearmodifiers --file -
    else
        # type login <tab> password
        echo -e "$login\t$pass" | xdotool type --clearmodifiers --file -
    fi
fi
